---
# tasks file for http
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy config
  template: 
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
  notify:
    - restart nginx service

- name: Copy files
  copy: 
    src: files/
    dest: "{{ app_work_dir }}"
    owner: root
    group: root
  notify:
    - restart nginx service
